### ISSUE TITLE
read in basic data file

### ISSUE THREAD

**Issue by marthageb** [marthageb/practice#1]
What type of data does it need to be?

**Comment by marthageb** [comment]
@noelleje how do I do this?

**Comment by noelleje** [comment]
I can solve this. No problem.

On Thu, Oct 1, 2015 at 3:05 PM, marthageb <notifications@github.com> wrote:

> @noelleje <https://github.com/noelleje> how do I do this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/marthageb/practice/issues/1#issuecomment-144862690>.
>



-- 
Noelle Espinosa
Graduate Student
School of Natural Resources and the Environment
University of Arizona

**Comment by rgallery** [comment]
@marthageb leave me out of this!
